Use json editor
asyml/stave pull request #137
Opened 2020-11-11 05:11 UTC by cyrexin

This PR adds the json editor component. #129  

### Description of changes
User is now able to edit the json (ontology & config) in a json editor (https://github.com/josdejong/jsoneditor) instead of plain text.

### Possible influences of this PR
n/a

### Demonstration of results
![json_editor](https://user-images.githubusercontent.com/16990133/98771403-60326b80-23b2-11eb-8449-41488593b6e3.gif)

2020-11-11 17:00 UTC, hunterhector reviewed
Interesting. This looks cool. Any ideas on travis failing?

2020-11-11 17:46 UTC, cyrexin commented on src/app/components/jsonEditor/JsonEditor.tsx
> +}
Done

2020-11-11 17:46 UTC, cyrexin commented on src/app/components/jsonEditor/index.tsx
> +export { default } from './JsonEditor';
Done

2020-11-11 17:47 UTC, cyrexin commented
> Interesting. This looks cool. Any ideas on travis failing?

Fix the travis test by the guidance here: https://jestjs.io/docs/en/webpack#mocking-css-modules

2020-11-11 20:12 UTC, hunterhector reviewed
This seems to work well. If we have a JSON Schema for this, how can we add it to the JsonEditor component?

2020-11-11 20:32 UTC, cyrexin commented
> This seems to work well. If we have a JSON Schema for this, how can we add it to the JsonEditor component?

As the example shows [here](https://github.com/josdejong/jsoneditor/blob/develop/examples/07_json_schema_validation.html), you can provide the schema as a param and the jsoneditor will do the validation.

2020-11-11 20:38 UTC, hunterhector commented
> > This seems to work well. If we have a JSON Schema for this, how can we add it to the JsonEditor component?
> 
> As the example shows [here](https://github.com/josdejong/jsoneditor/blob/develop/examples/07_json_schema_validation.html), you can provide the schema as a param and the jsoneditor will do the validation.

Shall we make this parameter available at the component level?

https://github.com/asyml/stave/pull/137/files#diff-9ede13f0aee5572e8933d3ab41a8b6fc00270d6b179e6c482370c2882fa87253R16

Here, the `options` are specified and take the `onChangeText` function. Shall we make the option available to the outside caller, so we can easily add the `schema` option when using it?

2020-11-12 22:06 UTC, hunterhector requested changes
Let's expose the schema to the higher level caller either by exposing the whole option or just that parameter. I think we can make use of the schema very soon.

Btw, if the json fails the schema check, what would happen?

2020-11-16 21:40 UTC, hunterhector approved these changes

2020-11-16 21:40 UTC, merged